apiVersion : apps/v1
kind: Deployment
metadata:
  name: divineopsexpressaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: divineopsexpressaks 
    spec:
      containers:
        - name: divineopsexpressaks 
          image: agunuacr.azurecr.io/agunuworldexpressaks
          ports:
          - containerPort: 3000
