apiVersion : apps/v1
kind: Deployment
metadata:
  name: agunuworldexpressaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: agunuworldexpressaks 
    spec:
      containers:
        - name: agunuworldexpressaks 
          image: agunuacr.azurecr.io/agunuworldexpressaks
          ports:
          - containerPort: 3000
